//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.OrderDetailPromotionMappings = new HashSet<OrderDetailPromotionMapping>();
        }
    
        public int OrderDetailID { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public double FinalAmount { get; set; }
        public double TotalAmount { get; set; }
        public double Discount { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Status { get; set; }
        public string Notes { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<int> ProductType { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int ProductOrderType { get; set; }
        public int ItemQuantity { get; set; }
        public int OrderGroup { get; set; }
        public Nullable<int> TmpDetailId { get; set; }
        public string PromotionCode { get; set; }
        public Nullable<int> OrderPromotionMappingId { get; set; }
        public Nullable<int> OrderDetailPromotionMappingId { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Code { get; set; }
    
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailPromotionMapping> OrderDetailPromotionMappings { get; set; }
    }
}
