//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PointOfSaleDBEntities : DbContext
    {
        public PointOfSaleDBEntities()
            : base("name=PointOfSaleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryExtra> CategoryExtras { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DateReport> DateReports { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderDetailPromotionMapping> OrderDetailPromotionMappings { get; set; }
        public virtual DbSet<OrderPromotionMapping> OrderPromotionMappings { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductExtra> ProductExtras { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<PromotionDetail> PromotionDetails { get; set; }
        public virtual DbSet<Source> Sources { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
