//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExtra
    {
        public int ProductExtraId { get; set; }
        public string PrimaryProductCode { get; set; }
        public string ExtraProductCode { get; set; }
        public bool IsEnable { get; set; }
        public Nullable<bool> IsDisplayed { get; set; }
        public Nullable<int> MaxItem { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<decimal> TimeStamp { get; set; }
        public bool IsUsed { get; set; }
    }
}
