//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Id { get; set; }
        public int StoreCode { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public Nullable<bool> isAvailable { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int Type { get; set; }
        public Nullable<int> RoomRentMode { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public string ShortName { get; set; }
        public bool IsUsed { get; set; }
        public string AuthorizeCode { get; set; }
    }
}
