//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Text { get; set; }
        public Nullable<int> Status { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsCircle { get; set; }
        public int TableRow { get; set; }
        public int TableColumn { get; set; }
        public int SpanTableRow { get; set; }
        public int SpanTableColumn { get; set; }
        public int Floor { get; set; }
        public Nullable<int> CurrentOrderId { get; set; }
        public Nullable<System.DateTime> CurrentOrderDate { get; set; }
        public Nullable<int> ForOrderType { get; set; }
    }
}
