//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryExtraViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<CategoryExtra>
    {
        public virtual int CategoryExtraId { get; set; }
        public virtual int PrimaryCategoryCode { get; set; }
        public virtual int ExtraCategoryCode { get; set; }
        public virtual bool IsEnable { get; set; }
    	public CategoryExtraViewModel() : base() { }
            public CategoryExtraViewModel(CategoryExtra entity) : base(entity) { }
    }
}
