//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<Customer>
    {
        public virtual int CustomerId { get; set; }
        public virtual string CustomerName { get; set; }
        public virtual string Address { get; set; }
        public virtual string PhoneNumber { get; set; }
        public virtual string Email { get; set; }
        public virtual Nullable<int> Nationality { get; set; }
        public virtual string Notes { get; set; }
    	public CustomerViewModel() : base() { }
            public CustomerViewModel(Customer entity) : base(entity) { }
    }
}
