//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<OrderDetail>
    {
        
    
        public virtual int OrderDetailID { get; set; }
        public virtual int OrderId { get; set; }
        public virtual int ProductId { get; set; }
        public virtual string ProductCode { get; set; }
        public virtual string ProductName { get; set; }
        public virtual double FinalAmount { get; set; }
        public virtual double TotalAmount { get; set; }
        public virtual double Discount { get; set; }
        public virtual int Quantity { get; set; }
        public virtual System.DateTime OrderDate { get; set; }
        public virtual int Status { get; set; }
        public virtual string Notes { get; set; }
        public virtual Nullable<double> TaxValue { get; set; }
        public virtual double UnitPrice { get; set; }
        public virtual Nullable<int> ProductType { get; set; }
        public virtual Nullable<int> ParentId { get; set; }
        public virtual int ProductOrderType { get; set; }
        public virtual int ItemQuantity { get; set; }
        public virtual int OrderGroup { get; set; }
        public virtual Nullable<int> TmpDetailId { get; set; }
        public virtual string PromotionCode { get; set; }
        public virtual Nullable<int> OrderPromotionMappingId { get; set; }
        public virtual Nullable<int> OrderDetailPromotionMappingId { get; set; }
        public virtual Nullable<bool> Active { get; set; }
        public virtual string Code { get; set; }
    
    	public OrderDetailViewModel() : base() { }
            public OrderDetailViewModel(OrderDetail entity) : base(entity) { }
    }
}
