//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class OrderViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<Order>
    {
        
    
        public virtual int OrderId { get; set; }
        public virtual string OrderCode { get; set; }
        public virtual System.DateTime CheckInDate { get; set; }
        public virtual Nullable<System.DateTime> CheckOutDate { get; set; }
        public virtual Nullable<System.DateTime> ApproveDate { get; set; }
        public virtual double TotalAmount { get; set; }
        public virtual double Discount { get; set; }
        public virtual double DiscountOrderDetail { get; set; }
        public virtual double FinalAmount { get; set; }
        public virtual int OrderStatus { get; set; }
        public virtual int OrderType { get; set; }
        public virtual string Notes { get; set; }
        public virtual string FeeDescription { get; set; }
        public virtual string CheckInPerson { get; set; }
        public virtual string CheckOutPerson { get; set; }
        public virtual string ApprovePerson { get; set; }
        public virtual Nullable<int> CustomerID { get; set; }
        public virtual Nullable<int> SourceID { get; set; }
        public virtual Nullable<int> TableId { get; set; }
        public virtual bool IsFixedPrice { get; set; }
        public virtual Nullable<System.DateTime> LastRecordDate { get; set; }
        public virtual string ServedPerson { get; set; }
        public virtual string DeliveryAddress { get; set; }
        public virtual int DeliveryStatus { get; set; }
        public virtual string DeliveryPhone { get; set; }
        public virtual string DeliveryCustomer { get; set; }
        public virtual int TotalInvoicePrint { get; set; }
        public virtual double VAT { get; set; }
        public virtual double VATAmount { get; set; }
        public virtual int NumberOfGuest { get; set; }
        public virtual int GroupPaymentStatus { get; set; }
        public virtual string Att1 { get; set; }
        public virtual string Att2 { get; set; }
        public virtual string Att3 { get; set; }
        public virtual string Att4 { get; set; }
        public virtual string Att5 { get; set; }
        public virtual string PromotionCode { get; set; }
        public virtual string PasswordWifi { get; set; }
        public virtual Nullable<int> CustomerType { get; set; }
        public virtual Nullable<System.DateTime> LastModifiedPayment { get; set; }
        public virtual Nullable<System.DateTime> LastModifiedOrderDetail { get; set; }
        public virtual Nullable<bool> Active { get; set; }
        public virtual string PaymentCode { get; set; }
        public virtual Nullable<int> PersonCount { get; set; }
    
    	public OrderViewModel() : base() { }
            public OrderViewModel(Order entity) : base(entity) { }
    }
}
