//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPromotionMappingViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<OrderPromotionMapping>
    {
        public virtual int Id { get; set; }
        public virtual int OrderId { get; set; }
        public virtual string PromotionCode { get; set; }
        public virtual string PromotionDetailCode { get; set; }
        public virtual int MappingIndex { get; set; }
        public virtual Nullable<decimal> DiscountAmount { get; set; }
        public virtual Nullable<int> DiscountRate { get; set; }
        public virtual Nullable<int> TmpMappingId { get; set; }
    
    	public OrderPromotionMappingViewModel() : base() { }
            public OrderPromotionMappingViewModel(OrderPromotionMapping entity) : base(entity) { }
    }
}
