//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<Payment>
    {
        public virtual int PaymentID { get; set; }
        public virtual int OrderId { get; set; }
        public virtual double Amount { get; set; }
        public virtual string CurrencyCode { get; set; }
        public virtual decimal FCAmount { get; set; }
        public virtual string Notes { get; set; }
        public virtual System.DateTime PayTime { get; set; }
        public virtual int Status { get; set; }
        public virtual int Type { get; set; }
        public virtual string CardCode { get; set; }
        public virtual Nullable<bool> Active { get; set; }
        public virtual string Code { get; set; }
    
    	public PaymentViewModel() : base() { }
            public PaymentViewModel(Payment entity) : base(entity) { }
    }
}
