//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class ProductViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<Product>
    {
        public virtual int ProductId { get; set; }
        public virtual string Code { get; set; }
        public virtual string ProductName { get; set; }
        public virtual string ShortName { get; set; }
        public virtual double Price { get; set; }
        public virtual string PicURL { get; set; }
        public virtual int CatID { get; set; }
        public virtual Nullable<bool> IsAvailable { get; set; }
        public virtual double DiscountPercent { get; set; }
        public virtual double DiscountPrice { get; set; }
        public virtual int ProductType { get; set; }
        public virtual int DisplayOrder { get; set; }
        public virtual Nullable<bool> HasExtra { get; set; }
        public virtual bool IsFixedPrice { get; set; }
        public virtual int PosX { get; set; }
        public virtual int PosY { get; set; }
        public virtual Nullable<int> ColorGroup { get; set; }
        public virtual int Group { get; set; }
        public virtual Nullable<bool> IsMenuDisplay { get; set; }
        public virtual Nullable<int> GeneralProductId { get; set; }
        public virtual string Att1 { get; set; }
        public virtual string Att2 { get; set; }
        public virtual string Att3 { get; set; }
        public virtual Nullable<int> MaxExtra { get; set; }
        public virtual Nullable<bool> IsMostOrder { get; set; }
        public virtual bool IsUsed { get; set; }
        public virtual Nullable<int> ProductParentId { get; set; }
        public virtual int PrintGroup { get; set; }
        public virtual bool IsDefaultChildProduct { get; set; }
    	public ProductViewModel() : base() { }
            public ProductViewModel(Product entity) : base(entity) { }
    }
}
