//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExtraViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<ProductExtra>
    {
        public virtual int ProductExtraId { get; set; }
        public virtual string PrimaryProductCode { get; set; }
        public virtual string ExtraProductCode { get; set; }
        public virtual bool IsEnable { get; set; }
        public virtual Nullable<bool> IsDisplayed { get; set; }
        public virtual Nullable<int> MaxItem { get; set; }
        public virtual Nullable<double> Price { get; set; }
        public virtual Nullable<decimal> TimeStamp { get; set; }
        public virtual bool IsUsed { get; set; }
    	public ProductExtraViewModel() : base() { }
            public ProductExtraViewModel(ProductExtra entity) : base(entity) { }
    }
}
