//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionDetailViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<PromotionDetail>
    {
        public virtual int PromotionDetailID { get; set; }
        public virtual string PromotionCode { get; set; }
        public virtual string RegExCode { get; set; }
        public virtual Nullable<double> MinOrderAmount { get; set; }
        public virtual Nullable<double> MaxOrderAmount { get; set; }
        public virtual string BuyProductCode { get; set; }
        public virtual Nullable<int> MinBuyQuantity { get; set; }
        public virtual Nullable<int> MaxBuyQuantity { get; set; }
        public virtual string GiftProductCode { get; set; }
        public virtual string PromotionDetailCode { get; set; }
        public virtual Nullable<int> GiftQuantity { get; set; }
        public virtual Nullable<decimal> DiscountAmount { get; set; }
        public virtual Nullable<int> DiscountRate { get; set; }
        public virtual Nullable<bool> Active { get; set; }
    	public PromotionDetailViewModel() : base() { }
            public PromotionDetailViewModel(PromotionDetail entity) : base(entity) { }
    }
}
