//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.ViewModels
{
      using POS.Repository.Entities;
    using System;
    using System.Collections.Generic;
    
    public partial class StoreViewModel:SkyWeb.DatVM.Mvc.BaseEntityViewModel<Store>
    {
        public virtual int Id { get; set; }
        public virtual int StoreCode { get; set; }
        public virtual string Name { get; set; }
        public virtual string Address { get; set; }
        public virtual string Lat { get; set; }
        public virtual string Lon { get; set; }
        public virtual Nullable<bool> isAvailable { get; set; }
        public virtual string Email { get; set; }
        public virtual string Phone { get; set; }
        public virtual string Fax { get; set; }
        public virtual Nullable<System.DateTime> CreateDate { get; set; }
        public virtual int Type { get; set; }
        public virtual Nullable<int> RoomRentMode { get; set; }
        public virtual Nullable<System.DateTime> ReportDate { get; set; }
        public virtual string ShortName { get; set; }
        public virtual bool IsUsed { get; set; }
        public virtual string AuthorizeCode { get; set; }
    	public StoreViewModel() : base() { }
            public StoreViewModel(Store entity) : base(entity) { }
    }
}
