//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities.Services
{
    using POS.Repository.Entities.Repositories;
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService:SkyWeb.DatVM.Data.BaseService<Order>, IOrderService
    {
      public OrderService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, IOrderRepository repository)
                : base(unitOfWork, repository)
            {
            }
        
    	}
        public partial interface IOrderService :  SkyWeb.DatVM.Data.IBaseService<Order>
        {
        }
}
