//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities.Services
{
    using POS.Repository.Entities.Repositories;
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExtraService:SkyWeb.DatVM.Data.BaseService<ProductExtra>, IProductExtraService
    {
      public ProductExtraService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, IProductExtraRepository repository)
                : base(unitOfWork, repository)
            {
            }
        
    	}
        public partial interface IProductExtraService :  SkyWeb.DatVM.Data.IBaseService<ProductExtra>
        {
        }
}
