//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities.Services
{
    using POS.Repository.Entities.Repositories;
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionDetailService:SkyWeb.DatVM.Data.BaseService<PromotionDetail>, IPromotionDetailService
    {
      public PromotionDetailService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, IPromotionDetailRepository repository)
                : base(unitOfWork, repository)
            {
            }
        
    	}
        public partial interface IPromotionDetailService :  SkyWeb.DatVM.Data.IBaseService<PromotionDetail>
        {
        }
}
