//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities.Services
{
    using POS.Repository.Entities.Repositories;
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionService:SkyWeb.DatVM.Data.BaseService<Promotion>, IPromotionService
    {
      public PromotionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, IPromotionRepository repository)
                : base(unitOfWork, repository)
            {
            }
        
    	}
        public partial interface IPromotionService :  SkyWeb.DatVM.Data.IBaseService<Promotion>
        {
        }
}
