//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities.Services
{
    using POS.Repository.Entities.Repositories;
    using POS.Repository.Response;
    using System;
    using System.Collections.Generic;
    
    public partial class StoreService:SkyWeb.DatVM.Data.BaseService<Store>, IStoreService
    {
      public StoreService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, IStoreRepository repository)
                : base(unitOfWork, repository)
            {
            }
    }
        public partial interface IStoreService :  SkyWeb.DatVM.Data.IBaseService<Store>
        {
        }
}
