//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Repository.Entities.Services
{
    using POS.Repository.Entities.Repositories;
    using System;
    using System.Collections.Generic;
    
    public partial class TableService:SkyWeb.DatVM.Data.BaseService<Table>, ITableService
    {
      public TableService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, ITableRepository repository)
                : base(unitOfWork, repository)
            {
            }
        
    	}
        public partial interface ITableService :  SkyWeb.DatVM.Data.IBaseService<Table>
        {
        }
}
